title: Royce AI Solutions Blog
description: AI Receptionists for Auto Dealerships and Medical Practices - Irvine, CA
baseurl: ""
url: "https://royceaisolutions.github.io"

theme: jekyll-theme-cayman
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Post defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: default
